/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.ayrtonguttier.projetointerdisciplinar1;

import br.com.ayrtonguttier.projetointerdisciplinar1.telas.TelaQuadrado;
import br.com.ayrtonguttier.projetointerdisciplinar1.telas.TelaTriangulo;
import br.com.ayrtonguttier.projetointerdisciplinar1.telas.TelaCone;
import br.com.ayrtonguttier.projetointerdisciplinar1.telas.TelaEquacaoSegundoGrau;
import br.com.ayrtonguttier.projetointerdisciplinar1.telas.TelaParalelepipedo;
import br.com.ayrtonguttier.projetointerdisciplinar1.telas.TelaFormas;
import br.com.ayrtonguttier.projetointerdisciplinar1.telas.TelaCilindro;
import br.com.ayrtonguttier.projetointerdisciplinar1.geometricos.objetos3d.Objeto3D;
import br.com.ayrtonguttier.projetointerdisciplinar1.geometricos.objetos2d.Objeto2D;
import br.com.ayrtonguttier.projetointerdisciplinar1.geometricos.objetos2d.Quadrado;
import br.com.ayrtonguttier.projetointerdisciplinar1.geometricos.objetos2d.TrianguloRetangulo;
import br.com.ayrtonguttier.projetointerdisciplinar1.equacoes.Equacao;
import br.com.ayrtonguttier.projetointerdisciplinar1.equacoes.EquacaoSegundoGrau;
import br.com.ayrtonguttier.projetointerdisciplinar1.geometricos.Filtros;
import br.com.ayrtonguttier.projetointerdisciplinar1.geometricos.objetos3d.Cilindro;
import br.com.ayrtonguttier.projetointerdisciplinar1.geometricos.objetos3d.ConeReto;
import br.com.ayrtonguttier.projetointerdisciplinar1.geometricos.objetos3d.Paralelepipedo;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ayrtonguttier
 */
public class ProjetoInterdisciplinar1 extends javax.swing.JFrame {

    private List<Objeto2D> objetos;
    private List<Objeto3D> objetos3D;
    private List<Equacao> equacoes;

    /**
     * Creates new form ProjetoInterdisciplinar
     */
    public ProjetoInterdisciplinar1() {
        objetos = new LinkedList<>();
        objetos3D = new LinkedList<>();
        equacoes = new LinkedList<>();
        initComponents();
        this.setLocationRelativeTo(null);
        atualizarQuantidades();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnQuadrado = new javax.swing.JButton();
        btnTriangulo = new javax.swing.JButton();
        btnMostrarObjetos2D = new javax.swing.JButton();
        lblQtdQuadrados = new javax.swing.JLabel();
        lblQtdTriangulos = new javax.swing.JLabel();
        lblTotalObj2D = new javax.swing.JLabel();
        btnMostrarQuadrados = new javax.swing.JButton();
        btnMostrarTriangulos = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnAdicionarCone = new javax.swing.JButton();
        btnAdicionarParalelepipedo = new javax.swing.JButton();
        btnAdicionarCilindro = new javax.swing.JButton();
        btnMostrarObjetos3D = new javax.swing.JButton();
        lblQtdCones = new javax.swing.JLabel();
        lblQtdParalelepipedos = new javax.swing.JLabel();
        lblQtdCilindros = new javax.swing.JLabel();
        lblQtd3d = new javax.swing.JLabel();
        btnMostrarCones = new javax.swing.JButton();
        btnMostrarParalelepipedos = new javax.swing.JButton();
        btnMostrarCilindros = new javax.swing.JButton();
        btnSalvar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnAbrir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnAddEquacao = new javax.swing.JButton();
        lblQtdEquacoes = new javax.swing.JLabel();
        btnMostrarEquacoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto Interdisciplinar");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Objetos 2D"));

        btnQuadrado.setText("Adicionar Quadrado");
        btnQuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuadradoActionPerformed(evt);
            }
        });

        btnTriangulo.setText("Adicionar Triângulo");
        btnTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrianguloActionPerformed(evt);
            }
        });

        btnMostrarObjetos2D.setText("Mostrar Todos");
        btnMostrarObjetos2D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarObjetos2DActionPerformed(evt);
            }
        });

        lblQtdQuadrados.setText("Quantidade de quadrados: %d");

        lblQtdTriangulos.setText("Quantidade de triângulos: %d");

        lblTotalObj2D.setText("Total de objetos 2D: %d");

        btnMostrarQuadrados.setText("Mostrar Quadrados");
        btnMostrarQuadrados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarQuadradosActionPerformed(evt);
            }
        });

        btnMostrarTriangulos.setText("Mostrar Triângulos");
        btnMostrarTriangulos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarTriangulosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnQuadrado)
                        .addGap(18, 18, 18)
                        .addComponent(lblQtdQuadrados)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, Short.MAX_VALUE)
                        .addComponent(btnMostrarQuadrados))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTotalObj2D)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarObjetos2D))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblQtdTriangulos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarTriangulos)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnQuadrado)
                    .addComponent(lblQtdQuadrados)
                    .addComponent(btnMostrarQuadrados))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTriangulo)
                    .addComponent(lblQtdTriangulos)
                    .addComponent(btnMostrarTriangulos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarObjetos2D)
                    .addComponent(lblTotalObj2D))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Objetos 3D"));

        btnAdicionarCone.setText("Adicionar Cone");
        btnAdicionarCone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarConeActionPerformed(evt);
            }
        });

        btnAdicionarParalelepipedo.setText("Adicionar Paralelepípedo");
        btnAdicionarParalelepipedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarParalelepipedoActionPerformed(evt);
            }
        });

        btnAdicionarCilindro.setText("Adicionar Cilíndro");
        btnAdicionarCilindro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarCilindroActionPerformed(evt);
            }
        });

        btnMostrarObjetos3D.setText("Mostrar Todos");
        btnMostrarObjetos3D.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarObjetos3DActionPerformed(evt);
            }
        });

        lblQtdCones.setText("Quantidade de cones: %d");

        lblQtdParalelepipedos.setText("Quantidade de paralelepípedos: %d");

        lblQtdCilindros.setText("Quantidade de cilíndros: %d");

        lblQtd3d.setText("Total de objetos 3D: %d");

        btnMostrarCones.setText("Mostrar Cones");
        btnMostrarCones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarConesActionPerformed(evt);
            }
        });

        btnMostrarParalelepipedos.setText("Mostrar Paralelepipedos");
        btnMostrarParalelepipedos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarParalelepipedosActionPerformed(evt);
            }
        });

        btnMostrarCilindros.setText("Mostrar Cilindros");
        btnMostrarCilindros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCilindrosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdicionarParalelepipedo)
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblQtdCones)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarCones))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblQtdParalelepipedos)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                                .addComponent(btnMostrarParalelepipedos))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblQtd3d)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarObjetos3D))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lblQtdCilindros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnMostrarCilindros))))
                    .addComponent(btnAdicionarCone)
                    .addComponent(btnAdicionarCilindro))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarCone)
                    .addComponent(lblQtdCones)
                    .addComponent(btnMostrarCones))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarParalelepipedo)
                    .addComponent(lblQtdParalelepipedos)
                    .addComponent(btnMostrarParalelepipedos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdicionarCilindro)
                    .addComponent(lblQtdCilindros)
                    .addComponent(btnMostrarCilindros))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarObjetos3D)
                    .addComponent(lblQtd3d))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnAbrir.setText("Abrir");
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Equações"));

        btnAddEquacao.setText("Adicionar Equação Segundo Grau");
        btnAddEquacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEquacaoActionPerformed(evt);
            }
        });

        lblQtdEquacoes.setText("Quantidade de equações: %d");

        btnMostrarEquacoes.setText("Mostrar Equações");
        btnMostrarEquacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarEquacoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddEquacao)
                .addGap(18, 18, 18)
                .addComponent(lblQtdEquacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMostrarEquacoes)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddEquacao)
                    .addComponent(lblQtdEquacoes)
                    .addComponent(btnMostrarEquacoes))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnSair)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAbrir)
                        .addGap(18, 18, 18)
                        .addComponent(btnSalvar))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar)
                    .addComponent(btnSair)
                    .addComponent(btnAbrir))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnQuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuadradoActionPerformed
        // TODO add your handling code here:
        TelaQuadrado tela = new TelaQuadrado(this, true, objetos);
        tela.setVisible(true);
        atualizarQuantidades();
    }//GEN-LAST:event_btnQuadradoActionPerformed

    private void btnMostrarObjetos2DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarObjetos2DActionPerformed
        // TODO add your handling code here:
        TelaFormas tela = new TelaFormas(this, true);
        tela.exibir(objetos);
    }//GEN-LAST:event_btnMostrarObjetos2DActionPerformed

    private void btnTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrianguloActionPerformed
        // TODO add your handling code here:
        TelaTriangulo tela = new TelaTriangulo(this, true, objetos);
        tela.setVisible(true);
        atualizarQuantidades();
    }//GEN-LAST:event_btnTrianguloActionPerformed

    private void btnAdicionarConeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarConeActionPerformed
        // TODO add your handling code here:
        TelaCone tela = new TelaCone(this, true, objetos3D);
        tela.setVisible(true);

    }//GEN-LAST:event_btnAdicionarConeActionPerformed

    private void btnAdicionarParalelepipedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarParalelepipedoActionPerformed
        // TODO add your handling code here:
        TelaParalelepipedo tela = new TelaParalelepipedo(this, true, objetos3D);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAdicionarParalelepipedoActionPerformed

    private void btnAdicionarCilindroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarCilindroActionPerformed
        // TODO add your handling code here:
        TelaCilindro tela = new TelaCilindro(this, true, objetos3D);
        tela.setVisible(true);
    }//GEN-LAST:event_btnAdicionarCilindroActionPerformed

    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:

        JFileChooser fChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivo do projeto interdisciplinar (*.pi)", "pi");
        fChooser.addChoosableFileFilter(filter);
        fChooser.setFileFilter(filter);
        int result = fChooser.showSaveDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {

            File f = fChooser.getSelectedFile();

            if (!f.getAbsolutePath().endsWith(".pi")) {
                f = new File(f.getAbsolutePath() + ".pi");
            }

            if (f.exists()) {
                f.delete();
            }

            try {
                f.createNewFile();
                try ( FileWriter writer = new FileWriter(f)) {
                    for (Objeto2D o : objetos) {
                        writer.append(o.criarRegistro() + "\n");
                    }
                    for (Objeto3D o : objetos3D) {
                        writer.append(o.criarRegistro() + "\n");
                    }
                    for (Equacao e : equacoes) {
                        writer.append(e.criarRegistro());
                    }
                }

            } catch (IOException ex) {
                Logger.getLogger(ProjetoInterdisciplinar1.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnSalvarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void limparDados() {
        objetos.clear();
        objetos3D.clear();
        atualizarQuantidades();
    }

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed

        JFileChooser fChooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("Arquivo do projeto interdisciplinar (*.pi)", "pi");
        fChooser.addChoosableFileFilter(filter);
        fChooser.setFileFilter(filter);
        int result = fChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            limparDados();
            File f = fChooser.getSelectedFile();
            try {

                BufferedReader reader = new BufferedReader(new FileReader(f));
                String linha;
                while ((linha = reader.readLine()) != null) {
                    String[] dados = linha.split(";");
                    try {

                        switch (Factory.getTipo(linha)) {
                            case Factory.OBJETO2D:
                                objetos.add(Factory.criarObjeto(linha));
                                break;
                            case Factory.OBJETO3D:
                                objetos3D.add(Factory.criarObjeto3D(linha));
                                break;
                            case Factory.EQUACAO:
                                equacoes.add(Factory.criarEquacao(linha));
                                break;
                            default:
                                break;
                        }
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(this, "Formato do arquivo inválido", "Erro ao abrir arquivo.", JOptionPane.ERROR_MESSAGE);
                        limparDados();
                        return;
                    }
                }

                reader.close();

            } catch (IOException ex) {
                Logger.getLogger(ProjetoInterdisciplinar1.class.getName()).log(Level.SEVERE, null, ex);
            }
            atualizarQuantidades();
        }
    }//GEN-LAST:event_btnAbrirActionPerformed

    private void btnMostrarObjetos3DActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarObjetos3DActionPerformed
        // TODO add your handling code here:
        TelaFormas tela = new TelaFormas(this, true);
        tela.exibir(objetos3D);

    }//GEN-LAST:event_btnMostrarObjetos3DActionPerformed

    private void btnMostrarQuadradosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarQuadradosActionPerformed
        TelaFormas tela = new TelaFormas(this, true);
        tela.exibir(Filtros.getQuadrados(objetos));

    }//GEN-LAST:event_btnMostrarQuadradosActionPerformed

    private void btnMostrarTriangulosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarTriangulosActionPerformed
        TelaFormas tela = new TelaFormas(this, true);
        tela.exibir(Filtros.getTriangulos(objetos));
    }//GEN-LAST:event_btnMostrarTriangulosActionPerformed

    private void btnMostrarConesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarConesActionPerformed
        TelaFormas tela = new TelaFormas(this, true);
        tela.exibir(Filtros.getCones(objetos3D));
    }//GEN-LAST:event_btnMostrarConesActionPerformed

    private void btnMostrarParalelepipedosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarParalelepipedosActionPerformed
        TelaFormas tela = new TelaFormas(this, true);
        tela.exibir(Filtros.getParalelepipedos(objetos3D));
    }//GEN-LAST:event_btnMostrarParalelepipedosActionPerformed

    private void btnMostrarCilindrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCilindrosActionPerformed
        TelaFormas tela = new TelaFormas(this, true);
        tela.exibir(Filtros.getCilindros(objetos3D));
    }//GEN-LAST:event_btnMostrarCilindrosActionPerformed

    private void btnAddEquacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEquacaoActionPerformed
        TelaEquacaoSegundoGrau tela = new TelaEquacaoSegundoGrau(this, true, equacoes);
        tela.setVisible(true);
        atualizarQuantidades();
    }//GEN-LAST:event_btnAddEquacaoActionPerformed

    private void btnMostrarEquacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarEquacoesActionPerformed
        // TODO add your handling code here:
        TelaFormas tela = new TelaFormas(this, true);
        tela.exibir(equacoes);
    }//GEN-LAST:event_btnMostrarEquacoesActionPerformed

    private void atualizarQuantidades() {

        Map<String, Integer> quantidades;
        quantidades = new HashMap<>();
        String tipo2d, tipo3d;
        tipo2d = Objeto2D.class.getTypeName();
        tipo3d = Objeto3D.class.getTypeName();

        for (Objeto2D item : objetos) {
            int qtd = quantidades.getOrDefault(item.getClass().getTypeName(), 0);
            quantidades.put(item.getClass().getTypeName(), qtd + 1);

            int total = quantidades.getOrDefault(tipo2d, 0);
            quantidades.put(tipo2d, total + 1);
        }

        for (Objeto3D item : objetos3D) {
            int qtd = quantidades.getOrDefault(item.getClass().getTypeName(), 0);
            quantidades.put(item.getClass().getTypeName(), qtd + 1);

            int total = quantidades.getOrDefault(tipo3d, 0);
            quantidades.put(tipo3d, total + 1);
        }

        lblQtdQuadrados.setText(String.format("Quantidade de quadrados: %d", quantidades.getOrDefault(Quadrado.class.getTypeName(), 0)));
        lblQtdTriangulos.setText(String.format("Quantidade de quadrados: %d", quantidades.getOrDefault(TrianguloRetangulo.class.getTypeName(), 0)));
        lblTotalObj2D.setText(String.format("Total de objetos 2D: %d", quantidades.getOrDefault(tipo2d, 0)));

        lblQtdCones.setText(String.format("Quantidade de cones: %d", quantidades.getOrDefault(ConeReto.class.getTypeName(), 0)));
        lblQtdParalelepipedos.setText(String.format("Quantidade de paralelepípedos: %d", quantidades.getOrDefault(Paralelepipedo.class.getTypeName(), 0)));
        lblQtdCilindros.setText(String.format("Quantidade de cilíndros: %d", quantidades.getOrDefault(Cilindro.class.getTypeName(), 0)));
        lblQtd3d.setText(String.format("Total de objetos 3D: %d", quantidades.getOrDefault(tipo3d, 0)));

        lblQtdEquacoes.setText(String.format("Total de equações: %d", equacoes.size()));

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoInterdisciplinar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoInterdisciplinar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoInterdisciplinar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoInterdisciplinar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoInterdisciplinar1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JButton btnAddEquacao;
    private javax.swing.JButton btnAdicionarCilindro;
    private javax.swing.JButton btnAdicionarCone;
    private javax.swing.JButton btnAdicionarParalelepipedo;
    private javax.swing.JButton btnMostrarCilindros;
    private javax.swing.JButton btnMostrarCones;
    private javax.swing.JButton btnMostrarEquacoes;
    private javax.swing.JButton btnMostrarObjetos2D;
    private javax.swing.JButton btnMostrarObjetos3D;
    private javax.swing.JButton btnMostrarParalelepipedos;
    private javax.swing.JButton btnMostrarQuadrados;
    private javax.swing.JButton btnMostrarTriangulos;
    private javax.swing.JButton btnQuadrado;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JButton btnTriangulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblQtd3d;
    private javax.swing.JLabel lblQtdCilindros;
    private javax.swing.JLabel lblQtdCones;
    private javax.swing.JLabel lblQtdEquacoes;
    private javax.swing.JLabel lblQtdParalelepipedos;
    private javax.swing.JLabel lblQtdQuadrados;
    private javax.swing.JLabel lblQtdTriangulos;
    private javax.swing.JLabel lblTotalObj2D;
    // End of variables declaration//GEN-END:variables
}
